### ISSUE TITLE
Transform issue

### ISSUE THREAD

**Issue by Rajchary** [mieszko4/react-native-zoom-us-test#63]
Hello community, I would like to pull the same setup but without using typescript. I have been following some docs and they aren't much helpful. Is it possible to build the same app by not using typescript if YES can any one please help me out here :)

**Comment by mieszko4** [comment]
Hey,
I do not recommend going away from TS

In any case if you really need it, you would need to:
1. create new react-native app (see https://reactnative.dev/blog/2017/03/13/introducing-create-react-native-app)
2. add `react-native-zoom-us` lib
3. copy content of App.tsx and related files and remove the type annotations so that the code becomes JS

**Comment by Rajchary** [comment]
Thank you @mieszko4 but as you mentioned I figured it's not the best way to run away from TS so I have been continuing with TS but now I ran into some other issue now :( .
while we join the meeting we'll get a push notification saying that the meeting in progress so my issue here, is there anyway to customize this notification to include some action buttons in it like leave-meeting button in that notification. I have gone through the library source repo code to find a way to customize it but I haven't found anything. If there is a way can you please help me out here :) .

**Comment by mieszko4** [comment]
Not sure about the customization of push. The lib is just a bridge over Zoom SDK (https://developers.zoom.us/) so if it is possible to customize in their native Android/iOS then it will be also possible to adjust the bridge for customization.
